### ISSUE TITLE
Tuning the model for recall

### ISSUE THREAD

**Issue by liangw89** [msrocean/Tik_Tok#10]
Hi, 

It seems that the model in the DL_Experiments/ow_attack.py is tuned for precision. Would you like to share the model for recall? 

Thanks,
Liang

**Comment by notem** [comment]
The OW DF model is tuned by adjusting the prediction threshold value. The script as it stands should give you precision and recall metrics for a number of different threshold values (e.g. lower threshold values will improve recall). 
The threshold values used for tuning is defined [here](https://github.com/msrocean/Tik_Tok/blob/master/DL_Experiments/ow_attack.py#L164) and you can choose lower values than what is currently used to *maybe* improve recall at a further cost to precision.
