### ISSUE TITLE
the raw data

### ISSUE THREAD

**Issue by WF-CIL** [msrocean/Tik_Tok#24]
Hello, 
I would like to ask, the data set in the raw data link you gave is not the same as the data set which only contains the direction sequence information given in the paper on Deep Fingerprinting, so how did you get the data set in the raw data link? Is it obtained by processing the dataset of Deep Fingerprinting?

**Comment by msrocean** [comment]
Hi, we collected the raw dataset from the authors of the Deep Fingerprinting paper. We get the timing and direction information by processing the dataset of Deep Fingerprinting. Because of the storage limitation, we discarded the raw data and kept only the necessary timing and directional information.

**Comment by WF-CIL** [comment]
Thank you very much for your reply, you have shown that https://drive.google.com/drive/folders/1k6X8PjKTXNalCiUQudx-HyqoAXVXRknL is the raw data given in the Deep Fingerprinting article. But when I checked the Deep Fingerprinting article's publicly available code repository https://github.com/deep-fingerprinting/df and found the publicly available dataset chain https://drive.google.com/drive/folders/ The dataset contained in 1kxjqlaWWJbMW56E3kbXlttqcKJFkeCy6 is not the same as the raw data you gave, this one contains only orientation sequences. Where did you get the raw data containing the time information?

**Comment by msrocean** [comment]
I see the confusion. Because we worked in the same research group, we have had the .pcap files at that time and for Tik-Tok paper we extracted the timing information from the same raw files. We do not have those .pcap files available now.

**Comment by WF-CIL** [comment]
I understand and thank you for your patience.
