### ISSUE TITLE
Directional time features for Undefended dataset

### ISSUE THREAD

**Issue by liangw89** [msrocean/Tik_Tok#9]
Hi, 

The "Undefended" dataset (published at https://github.com/deep-fingerprinting/df) does not have timing information. So how to generate directional time for this dataset? 

Best

**Comment by msrocean** [comment]
Hi, 
Good catch! I have updated the README with Google drive URL for raw data. 
Pasting the URL for you here as well: https://drive.google.com/drive/folders/1k6X8PjKTXNalCiUQudx-HyqoAXVXRknL?usp=sharing  

I hope that helps and let me know if you have issues with the google drive access.

thanks.

**Comment by liangw89** [comment]
Thanks!

**Comment by liangw89** [comment]
It seems that the Undefended dataset in the google drive only has the closed-world data. Would you like to share the open-world data? 

Thanks,
Liang

**Comment by msrocean** [comment]
Hi Liang,

Sorry! it took some time to process the dataset to make publicly available. You can find those OW datasets in the same g-drive URL. 

Please let me know if you have any more questions.

thanks
--

**Comment by liangw89** [comment]
Thanks a lot!
